-- =========================================
-- Supabase RPC Function for Vanna AI Queries
-- =========================================
-- This function allows safe execution of SELECT queries
-- generated by Vanna AI directly in PostgreSQL
--
-- SECURITY: Only allows SELECT statements, blocks dangerous operations

CREATE OR REPLACE FUNCTION execute_vanna_query(query_text TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSONB;
    normalized_query TEXT;
BEGIN
    -- Normalize query (remove extra whitespace)
    normalized_query := TRIM(regexp_replace(query_text, '\s+', ' ', 'g'));

    -- Security check: Only allow SELECT or WITH statements
    IF NOT (normalized_query ~* '^\s*(SELECT|WITH)\s') THEN
        RAISE EXCEPTION 'Only SELECT and WITH queries are allowed';
    END IF;

    -- Security check: Block dangerous operations
    IF normalized_query ~* '\b(DROP|DELETE|UPDATE|INSERT|ALTER|CREATE|TRUNCATE|GRANT|REVOKE)\b' THEN
        RAISE EXCEPTION 'Dangerous SQL operations are not allowed';
    END IF;

    -- Security check: Block multiple statements
    IF normalized_query ~ ';\s*\w' THEN
        RAISE EXCEPTION 'Multiple statements are not allowed';
    END IF;

    -- Execute the query and return results as JSONB
    EXECUTE 'SELECT COALESCE(jsonb_agg(row_to_json(t)), ''[]''::jsonb) FROM (' || query_text || ') t'
    INTO result;

    RETURN result;

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Query execution error: %', SQLERRM;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION execute_vanna_query(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION execute_vanna_query(TEXT) TO service_role;

-- =========================================
-- USAGE INSTRUCTIONS
-- =========================================
-- 1. Run this SQL in Supabase SQL Editor
-- 2. Update database.py to use this RPC function
-- 3. Now Vanna AI SQL will execute directly in PostgreSQL!
--
-- Example usage from Python:
-- result = supabase.rpc('execute_vanna_query', {'query_text': vanna_sql}).execute()
